### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Usama-Aslam23** [WillKoehrsen/Bokeh-Python-Visualization#2]
I followed all the instructions but when I run bokeh serve command the page opens in browser but doesn't display anything, when I inspect element, I see this message. What could be the problem?

**Comment by Usama-Aslam23** [comment]
Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x0000020988D426D8>: unexpected attribute 'value' to RangeSlider, possible attributes are callback, callback_policy, callback_throttle, css_classes, disabled, end, height, js_event_callbacks, js_property_callbacks, name, orientation, range, sizing_mode, start, step, subscribed_events, tags, title or width
File "has_props.py", line 277, in __setattr__:
(name, self.__class__.__name__, text, nice_join(matches))) Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\application\handlers\code_runner.py", line 81, in run
    exec(self._code, module.__dict__)
  File "E:\Bokeh-Python-Visualization-master\bokeh_app\main.py", line 31, in <module>
    tab1 = histogram_tab(flights)
  File "E:\Bokeh-Python-Visualization-master\bokeh_app\scripts\histogram.py", line 137, in histogram_tab
    step = 5, title = 'Range of Delays (min)')
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\model.py", line 226, in __init__
    super(Model, self).__init__(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\has_props.py", line 241, in __init__
    setattr(self, name, value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\has_props.py", line 277, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'value' to RangeSlider, possible attributes are callback, callback_policy, callback_throttle, css_classes, disabled, end, height, js_event_callbacks, js_property_callbacks, name, orientation, range, sizing_mode, start, step, subscribed_events, tags, title or width

**Comment by WillKoehrsen** [comment]
I am not able to recreate the issue. What version of Bokeh are you running?

I am using Bokeh version 0.12.16.

I would suggest updating to the newest version of Bokeh from the command line using `pip install -U bokeh`
