### ISSUE TITLE
AttributeError: 'str' object has no attribute 'append' using Python 3.5.3 and bokeh 0.12.16 

### ISSUE THREAD

**Issue by dazzag24** [WillKoehrsen/Bokeh-Python-Visualization#3]
I had to comment out these 2 lines in scripts/draw_map.py

hover_line.renderers.append(lines_glyph)
hover_circle.renderers.append(circles_glyph)

otherwise I would receive the following error and a blank page in the browser.

2018-05-24 16:59:06,237 Starting Bokeh server version 0.12.16 (running on Tornado 5.0.2)
2018-05-24 16:59:06,243 Bokeh app running at: http://localhost:5006/bokeh_app
2018-05-24 16:59:06,243 Starting Bokeh server with process id: 18459
[18471:18493:0524/165906.877041:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
Created new window in existing browser session.
/home/foo/.virtualenvs/BokehDashbord-8BNqqEK8/lib/python3.5/site-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
2018-05-24 16:59:10,798 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7fe98e428fd0>: 'str' object has no attribute 'append'
File "draw_map.py", line 142, in make_plot:
hover_circle.renderers.append(circles_glyph) Traceback (most recent call last):
  File "/home/foo/.virtualenvs/BokehDashbord-8BNqqEK8/lib/python3.5/site-packages/bokeh/application/handlers/code_runner.py", line 163, in run
    exec(self._code, module.__dict__)
  File "/home/foo/code/BokehDashbord/bokeh_app/main.py", line 34, in <module>
    tab4 = map_tab(map_data, states)
  File "/home/foo/code/BokehDashbord/bokeh_app/scripts/draw_map.py", line 208, in map_tab
    p = make_plot(src, xs, ys)
  File "/home/foo/code/BokehDashbord/bokeh_app/scripts/draw_map.py", line 142, in make_plot
    hover_circle.renderers.append(circles_glyph)
AttributeError: 'str' object has no attribute 'append'

**Comment by WillKoehrsen** [comment]
Thanks for pointing this out. I have made the fix in `draw_map.py` in the `make_plot` function:

1. Remove the lines
`hover_circle.renderers.append(circles_glyph)`
and `hover_line.renderers.append(line_glyph)`

2. Replace by adding the `renderer` argument to the `HoverTool` creation code:

```python
# Hover tooltip for flight lines, assign only the line renderer
hover_line = HoverTool(tooltips=[('Airline', '@carrier'),
							('Number of Flights', '@count'),
							('Average Delay', '@mean_delay{0.0}'),
							('Max Delay', '@max_delay{0.0}'),
							('Min Delay', '@min_delay{0.0}')],
						         line_policy = 'next',
						         renderers = [lines_glyph])
```

```python
# Hover tooltip for origin and destination, assign only the circle renderer
hover_circle = HoverTool(tooltips=[('Origin', '@origin'),
						         ('Dest', '@dest'),
							 ('Distance (miles)', '@distance')],
						         renderers = [circles_glyph])
```

3. Move the `HoverTool` creation code to affect the definition for `circles_glyph` and `lines_glyph`. 

The most recent commit implements this change and the application is once again running.

**Comment by dazzag24** [comment]
Thanks.  That works now.

**Comment by willwillis** [comment]
Thanks for the article and for sharing the code. The Zip file linked to from the [Medium](https://towardsdatascience.com/data-visualization-with-bokeh-in-python-part-iii-a-complete-dashboard-dc6a86aa6e23) article doesn't contain [this](https://github.com/WillKoehrsen/Bokeh-Python-Visualization/issues/3) update.
